services:
  - type: web
    name: linguaflow
    env: node
    region: oregon
    plan: free
    buildCommand: export NODE_ENV=development && npm install && cd client && npm install && npm run build && cd .. && npx tsc
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: DEEPL_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
